### ISSUE TITLE
Conflict with VPP Admin Tools

### ISSUE THREAD

**Issue by deannreid** [DayZ-n-Chill/Colorful-HUD#3]
m_Player conflicts with VPP 

```
Can't compile "Mission" script module!

VPPAdminTools/5_Mission/vppadmintools\missiondebug.c(3): Multiple declaration of variable 'm_Player'

Runtime mode
CLI params: config serverDZ.cfg.active port 2501 profiles profiles adminlog  freezecheck  dologs  mod @GameLabs;@CF;@VPPAdminTools;@ROT_Dev; 
```

**Comment by DrkDevil** [comment]
![image](https://user-images.githubusercontent.com/8229881/222855683-a2bb5a20-63f1-4d77-a045-493db325b4d0.png)
VPP Admin tools has not been updated since _Nov 30, 2022 @ 3:53am_  Due to updates in DayZ 1.20 it wont compile.  This is not due to my mod but corrections that need to be made in their mod.  Specifically on line three in their code, as well as others.  You could for their tools from their repo and fix, but this is not a Colorful-HUD issue. 
![image](https://user-images.githubusercontent.com/8229881/222856030-2c3a8d15-7f70-4152-96b8-7739671a5abd.png)
****

**Comment by DrkDevil** [comment]
Found  possible work around. Will reopen.

**Comment by DrkDevil** [comment]
Well.  I had to reformat my machine last night.  When I did.  I created a new local server. With VPP and Colorful Hud.  
I had only these mods with the most current updated versions.   

SET "MODS=@CF;@VPPADMINTOOLS;@Colorful-HUD;"

I had absolutely no issues.  I cannot replicate the issue at all. 

@deannreid  Can you give me more information to the issue that might allow me to replicate it.

**Comment by DrkDevil** [comment]
@deannreid 
Note:  I would also put gamelabs after CF 

![image](https://user-images.githubusercontent.com/8229881/222923198-7ea0b6ed-2188-4a5d-950d-cb6bfdf802e6.png)

**Comment by DrkDevil** [comment]
Cant Replicate. Closing issue.

**Comment by deannreid** [comment]
Thanks, Must've just been a one-off then I guess, I'll keep testing.
